In [1]:
#numpy Array manipulation.

In [2]:
import numpy as np

In [5]:
arr= np.random.randint(1,10,(3,4))

In [6]:
arr

array([[3, 6, 1, 2],
       [6, 1, 5, 4],
       [1, 4, 3, 9]])

In [8]:
arr.reshape(2,6)

array([[3, 6, 1, 2, 6, 1],
       [5, 4, 1, 4, 3, 9]])

In [10]:
arr.reshape(2,-256325)  #it auto matically uderstand about second dimensional

array([[3, 6, 1, 2, 6, 1],
       [5, 4, 1, 4, 3, 9]])

In [11]:
arr.T

array([[3, 6, 1],
       [6, 1, 4],
       [1, 5, 3],
       [2, 4, 9]])

In [12]:
arr

array([[3, 6, 1, 2],
       [6, 1, 5, 4],
       [1, 4, 3, 9]])

In [13]:
arr.flatten()

array([3, 6, 1, 2, 6, 1, 5, 4, 1, 4, 3, 9])

In [14]:
arr1=np.array([1,2,3,4,5,5])

In [15]:
arr1

array([1, 2, 3, 4, 5, 5])

In [16]:
arr1.ndim

1

In [17]:
np.expand_dims(arr1,axis=1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [5]])

In [18]:
arr

array([[3, 6, 1, 2],
       [6, 1, 5, 4],
       [1, 4, 3, 9]])

In [19]:
np.squeeze(arr)

array([[3, 6, 1, 2],
       [6, 1, 5, 4],
       [1, 4, 3, 9]])

In [22]:
data = np.array([[1],[2],[3]])

In [23]:
data

array([[1],
       [2],
       [3]])

In [24]:
np.squeeze(data)

array([1, 2, 3])

In [25]:
arr1

array([1, 2, 3, 4, 5, 5])

In [27]:
np.repeat(arr1,3)  #for repeat the elemnet in array

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 5, 5, 5])

In [28]:
np.roll(arr1,2)

array([5, 5, 1, 2, 3, 4])

In [29]:
arr1

array([1, 2, 3, 4, 5, 5])

In [31]:
np.diag(arr1) #for making diagonal

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 5]])

In [32]:
#binary opeation in numpy

In [40]:
arr1=np.random.randint(1,50,(3,3))

In [41]:
arr1

array([[12,  9, 25],
       [25, 24,  8],
       [18, 26, 40]])

In [42]:
arr2=np.random.randint(1,50,(3,3))

In [43]:
arr2

array([[31, 14, 45],
       [20, 44, 17],
       [25, 13,  7]])

In [44]:
arr1+arr2

array([[43, 23, 70],
       [45, 68, 25],
       [43, 39, 47]])

In [45]:
arr1@arr2

array([[1177,  889,  868],
       [1455, 1510, 1589],
       [2078, 1916, 1532]])

In [46]:
arr1*arr2

array([[ 372,  126, 1125],
       [ 500, 1056,  136],
       [ 450,  338,  280]])

In [47]:
arr1/arr2

array([[0.38709677, 0.64285714, 0.55555556],
       [1.25      , 0.54545455, 0.47058824],
       [0.72      , 2.        , 5.71428571]])

In [48]:
arr1-arr2

array([[-19,  -5, -20],
       [  5, -20,  -9],
       [ -7,  13,  33]])

In [50]:
arr1%arr2

array([[12,  9, 25],
       [ 5, 24,  8],
       [18,  0,  5]])

In [51]:
arr1 ** arr2

array([[          0,  1796636465,  1895799737],
       [-1413876383,           0,           0],
       [-1845493760,  2025824256,   631242752]])

In [53]:
arr1 & arr2  #we are ding and operation

array([[12,  8,  9],
       [16,  8,  0],
       [16,  8,  0]])

In [56]:
~arr1  #neative operation

array([[-13, -10, -26],
       [-26, -25,  -9],
       [-19, -27, -41]])

In [57]:
arr1

array([[12,  9, 25],
       [25, 24,  8],
       [18, 26, 40]])

In [60]:
arr1|arr2  #or opeation 

array([[31, 15, 61],
       [29, 60, 25],
       [27, 31, 47]])

In [61]:
arr1>arr2

array([[False, False, False],
       [ True, False, False],
       [False,  True,  True]])

In [62]:
#String function in numpy

In [63]:
arr=np.array(['shaury' ,'rawat'])

In [64]:
np.char.upper(arr)  #this is convert into upper case using numpy

array(['SHAURY', 'RAWAT'], dtype='<U6')

In [66]:
np.char.title(arr)#convert title into upper case

array(['Shaury', 'Rawat'], dtype='<U6')

In [67]:
np.char.capitalize(arr)

array(['Shaury', 'Rawat'], dtype='<U6')

In [68]:
#mathmatical function in numy

In [69]:
arr1

array([[12,  9, 25],
       [25, 24,  8],
       [18, 26, 40]])

In [70]:
np.sin(arr1)

array([[-0.53657292,  0.41211849, -0.13235175],
       [-0.13235175, -0.90557836,  0.98935825],
       [-0.75098725,  0.76255845,  0.74511316]])

In [71]:
np.cos(arr1)

array([[ 0.84385396, -0.91113026,  0.99120281],
       [ 0.99120281,  0.42417901, -0.14550003],
       [ 0.66031671,  0.64691932, -0.66693806]])

In [74]:
np.tan(arr1)

array([[-0.63585993, -0.45231566, -0.13352641],
       [-0.13352641, -2.1348967 , -6.79971146],
       [-1.13731371,  1.17875355, -1.11721493]])

In [75]:
np.tanh(arr1)

array([[1.        , 0.99999997, 1.        ],
       [1.        , 1.        , 0.99999977],
       [1.        , 1.        , 1.        ]])

In [76]:
np.log10(arr1)

array([[1.07918125, 0.95424251, 1.39794001],
       [1.39794001, 1.38021124, 0.90308999],
       [1.25527251, 1.41497335, 1.60205999]])

In [77]:
np.exp(arr1)

array([[1.62754791e+05, 8.10308393e+03, 7.20048993e+10],
       [7.20048993e+10, 2.64891221e+10, 2.98095799e+03],
       [6.56599691e+07, 1.95729609e+11, 2.35385267e+17]])

In [78]:
np.sqrt(arr1)

array([[3.46410162, 3.        , 5.        ],
       [5.        , 4.89897949, 2.82842712],
       [4.24264069, 5.09901951, 6.32455532]])

In [79]:
np.power(arr1,2)

array([[ 144,   81,  625],
       [ 625,  576,   64],
       [ 324,  676, 1600]], dtype=int32)

In [80]:
np.mean(arr1)

20.77777777777778

In [82]:
np.median(arr1)

24.0

In [83]:
np.std(arr1)

9.6006687009902

In [84]:
np.var(arr1)

92.17283950617285

In [86]:
np.min(arr1)

8

In [87]:
np.max(arr1)

40